HTL-Memes-Scrum/HTL-Memes-Scrum/Controllers/MemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HTL_Memes_Scrum.Models;

namespace HTL_Memes_Scrum.Controllers
{
    public class MemeController : Controller
    {
        // GET: Meme
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult deleteMeme()
        //{
        //    MemeManager mm = new MemeManager();
        //    User user = (User)Session["user"];
        //    mm.deleteMemeFromDB(user.id);
        //}


    }
}

HTL-Memes-Scrum/HTL-Memes-Scrum/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HTL_Memes_Scrum.Models;
using HTL_Memes_Scrum.Models.models;

namespace HTL_Memes_Scrum.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            LoginUser lu = new LoginUser();
            return View(lu);
        }
        [HttpPost]
        public ActionResult Login(LoginUser lu)
        {

            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }


        public ActionResult UserEditor()
        {
            if ((Session["Admin"] != null) && (Convert.ToInt32(Session["Admin"]) == 1)) ;
            try
            {
                UserRepository dbm = UserRepository.GetInstance();

                return View(dbm.GetAllUsers());

            }
            catch (SqlException)
            {
                return View("Message", new Message("Datenbankfehler!", "", "Die Datenbank reagierte nicht!", "Bitte später erneut versuchen!"));
            }

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                UserRepository dbm = UserRepository.GetInstance();

                if (dbm.DeleteUser(id))
                {
                    return RedirectToAction("UserEditor");
                }
                else
                {
                    return View("Message", new Message("Benutzer löschen", "", "Der Benutzer konnte nicht gelöscht werden.", ""));
                }
            }
            catch (SqlException)
            {
                return View("Message", new Message("Datenbankfehler", "", "Probleme mit der Datenbank.", "Versuchen Sie es später erneut."));
            }
        }

        [HttpPost]
        public ActionResult Update(int id)
        {
            try
            {
                UserRepository dbm = UserRepository.GetInstance();

                if(dbm.GetUser(id) != null)
                {
                    return View(dbm.GetUser(id));
                }
                else
                {
                    return View("Message", new Message("Benutzer nicht vorhanden!", "", "Der Benutzer konnte nicht gefudnen werden.", ""));
                }
            }
            catch (MySqlException)
            {
                return View("Message", new Message("Datenbankfehler", "", "Probleme mit der Datenbank.", "Versuchen Sie es später erneut."));
            }
        }

        [HttpPost]
        public ActionResult Update(User user)
        {
            try
            {
                UserRepository dbm = UserRepository.GetInstance();

                if (dbm.GetUser(user.ID) != null)
                {
                    dbm.UpdateUser(user.ID, user);
                }
                else
                {
                    return View("Message", new Message("Benutzer nicht vollständig definiert!", "", "Bitte alle geforderten Daten angeben.", ""));
                }
            }
            catch (MySqlException)
            {
                return View("Message", new Message("Datenbankfehler", "", "Probleme mit der Datenbank.", "Versuchen Sie es später erneut."));
            }
        }
    }

}

HTL-Memes-Scrum/HTL-Memes-Scrum/Views/Shared/Footer.cshtml
<div id="footercontent">
    <ul>
        <li>
            @Html.ActionLink("Impressum", "imprint", "home")
            @Html.ActionLink("Kontakt", "contact", "home")
            @Html.ActionLink("Datenschutz", "dataprotection", "home")
        </li>
    </ul>

</div>

HTL-Memes-Scrum/HTL-Memes-Scrum/Views/Shared/Header.cshtml
<table id="HeaderTable">
        <tr id="HeaderRow">
            <td>
                <img id="Logo" src="~/Content/pictures/Logo.png"/>
            </td>
            <td id="ItemContainerHeader">
                <div class="AbstandItem"></div>
                <table>
                    <tr>
                        <td class="AbstandItem"></td>
                        <td><a href="/Home/Start"><img id="HomeBtn" src="~/Content/pictures/Header/HomeBtn.png" title="Home"/></a></td>
                        <td class="AbstandItem"></td>
                        <td><a href="/Home/Latest"><img id="LatestBtn" src="~/Content/pictures/Header/LatestBtn.png" title="Newest"/></a></td>
                        <td class="AbstandItem"></td>
                        <td><a href="/Home/Favorite"><img id="MostLikedBtn" src="~/Content/pictures/Header/MostLikedBtn.png" title="Favorites"/></a></td>
                        <td class="AbstandItem"></td>
                        <td>
                            <div class="categoryDD">
                                <img id="CategoryBtn" src="~/Content/pictures/Header/CategoryBtn.png" />
                                <div class="categoryDD-content">
                                    <a href="#">Link 1</a>
                                    <a href="#">Link 2</a>
                                    <a href="#">Link 3</a>
                                </div>
                            </div>
                        </td>
                        <td class="AbstandItem"></td>
                        <td><a href="/Home/Upload"><img id="UploadBtn" src="~/Content/pictures/Header/UploadBtn.png" title="Upload"/></a></td>
                        <td class="AbstandItem"></td>
                        <td><a href="/Home/SignIn"><img id="SignInBtn" src="~/Content/pictures/Header/SignInBtn.png" title="Login"/></a></td>
                        <td class="AbstandItem"></td>
                    </tr>
                </table>              
            </td>
            <td class="w3-container">
                <input id="Suchleiste" class="w3-input w3-border w3-animate-input w3-round-xxlarge" type="text" placeholder="Search">
            </td>
        </tr>
    </table>

HTL-Memes-Scrum/HTL-Memes-Scrum/Views/Shared/UserNavigation.cshtml
    <nav>
        <ul>

            <li>@Html.ActionLink("Start", "Index", "Meme")</li>
            <li>@Html.ActionLink("Registrieren", "Register", "User")</li>
            <li>@Html.ActionLink("Log in", "Login", "User")</li>
            <li>@Html.ActionLink("Userdaten anzeigen", "ShowData", "User")</li>
        </ul>
    </nav>

HTL-Memes-Scrum/HTL-Memes-Scrum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <header>
                @Html.Partial("Header")
            </header>
            </div>
     </div>

    <div class="container body-content">
        @RenderBody()
        <hr />


        <footer>
            @Html.Partial("Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>